steps:
    - id: "Go Unit Tests"
      name: golang
      args: ["go", "test", "main_test.go"]

    - id: "docker-compose"
      name: "gcr.io/$PROJECT_ID/docker-compose"
      args: ["up", "-d"]


    - id: "Verificando se a imagem realmente subiu"
      name: "gcr.io/$PROJECT_ID/challange-ci:latest"
      args: ["version"]

    images:
    - "gcr.io/$PROJECT_ID/challange-ci:latest"
