steps:
  - id: "Go Unit Tests"
    name: golang
    args: ["go", "test", "main_test.go"]

  - id: "docker-compose"
    name: "gcr.io/$PROJECT_ID/docker-compose"
    args: ["up", "-d"]

  - id: "Subindo imagem pro GCP registry"
    name: "gcr.io/$PROJECT_ID/docker-compose"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/challange-ci", "."]
